use_frameworks!

platform :ios, '9.0'

target 'SwipePopViewController_Example' do
  pod 'SwipePopViewController', :path => '../'

  target 'SwipePopViewController_Tests' do
    inherit! :search_paths
  end
end
