use_frameworks!

platform :ios, '9.0'

target 'SwipePopViewController_Example' do
  pod 'SwipePopViewController', :path => '../'

  target 'SwipePopViewController_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
